version: '3'
services:
  web:
    container_name: web
    build:
      context: .
    environment:
      VITE_GITHUB_ACCESS_TOKEN: ${VITE_GITHUB_ACCESS_TOKEN}
    ports:
      - 5173:5173
    volumes:
      - ./:/home/node/app:delegated

